[package]
name = "typed-jni"
version.workspace = true
edition.workspace = true

[features]
std = []
cache = ["uluru", "std"]

default = ["cache", "std"]

[dependencies]
uluru = { version = "3.1", optional = true }
