[package]
name = "example"
version.workspace = true
edition.workspace = true

[lib]
crate-type = ["lib", "cdylib"]

[dependencies]
typed-jni = { workspace = true, features = ["default"] }

jni = { version = "0.21", features = ["invocation"] }
