name: Publish

on:
  workflow_dispatch: { }

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: release
    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v5

      - name: Authenticate with crates.io
        uses: rust-lang/crates-io-auth-action@v1
        id: auth

      - name: Publish to crates.io
        run: cargo publish --package typed-jni-core --package typed-jni
        env:
          CARGO_REGISTRY_TOKEN: ${{ steps.auth.outputs.token }}
